# Generated by Django 3.2.3 on 2022-05-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220512_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_adress',
            new_name='customer_address',
        ),
    ]
