# Generated by Django 3.2.3 on 2022-05-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220519_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discont',
            new_name='discount',
        ),
    ]
